### ISSUE TITLE
Cannot destroy database

### ISSUE THREAD

**Issue by marcinwieprzkowicz** [hmalphettes/redisdown#18]
Hi,

I'm using express-pouchdb with redisdown on my heroku account. When I'm trying to destroy my database I got an error:
```
PouchDB.destroy() is deprecated and will be removed. Please use db.destroy() instead.
/Users/projects/node_modules/redisdown/node_modules/redis/index.js:1246
        throw new Error('unknown type of connection in createClient()');
              ^
Error: unknown type of connection in createClient()
    at Object.exports.createClient (/projects/pouchdb-server/node_modules/redisdown/node_modules/redis/index.js:1246:15)
    at Function.RedisDown.destroy (/projects/pouchdb-server/node_modules/redisdown/index.js:187:25)
    at callDestroy (/projects/pouchdb-server/node_modules/pouchdb/lib/adapters/leveldb/leveldb.js:1356:17)
    at /projects/pouchdb-server/node_modules/pouchdb/lib/adapters/leveldb/leveldb.js:1348:9
    at /projects/pouchdb-server/node_modules/pouchdb/node_modules/levelup/lib/levelup.js:136:18
    at Immediate._onImmediate (/projects/pouchdb-server/node_modules/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:65:7)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

My server code:
```
var expressPouchDB  = require('express-pouchdb');
var redisdown       = require('redisdown');
var pouchDB         = require('pouchdb');

var redisPouchDB    = pouchDB.defaults({
  db: redisdown,
  url: process.env.REDISCLOUD_URL
});

var app             = expressPouchDB(redisPouchDB, {
  mode: 'fullCouchDB'
});

app.set('port', (process.env.PORT || 5000));

new redisPouchDB('myDB');

app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});
```

Do you have any idea why this is happening? Did I miss something?

**Comment by hmalphettes** [comment]
@marcinwieprzkowicz I am not sure what is happening.
I can run the sample code you provided.
Can you let us know what code you run to destroy the database?

**Comment by hmalphettes** [comment]
Looking at the node-redis sources: https://github.com/NodeRedis/node_redis/blob/38ae7a7f507a71224e24a02d703a959f1b0fc657/index.js#L1246

I suspect that the value of `process.env.REDISCLOUD_URL` is not a valid URL.
For example if I use `url: 'redis://localhost:6379@user:pass'` on the first request to the pouchDB database I'll get in the console:
`[Error: unknown type of connection in createClient()]`
The correct URL is: 'redis://user:pass@localhost:6379'

Instead of catching the error and simply log it I guess we should do something more drastic?

**Comment by hmalphettes** [comment]
Closing for now. @marcinwieprzkowicz please let us know how it goes and re-open if you are still facing the problem.
