### ISSUE TITLE
db.createValueStream() does not work.

### ISSUE THREAD

**Issue by delaneyj** [hmalphettes/redisdown#19]
```javascript
db.batch().put('a','a').put('b','b').write(()=>{
    db.createReadStream({gte:'a',lte:'\u00ff'}).on('data',d=>{
        console.log(JSON.stringify(d,null,2))
    });
});
```
works just fine (as well as `createKeyStream`), but createValueStream() give back no values or errors but can catch the streams.on('end') with no results.  Same behavior if using `db.createReadStream({keys:false,values:true})`.

**Comment by hmalphettes** [comment]
Thanks for raising the issue. Working on a fix.

**Comment by delaneyj** [comment]
Sweet!
